name: Build and deploy container app to Azure Web App - HDeXpert

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  code-quality-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11.4"
    - uses: pre-commit/action@v3.0.1

  test:
    runs-on: 'ubuntu-latest'
    needs: code-quality-checks
    env:
      OPENAI_API_TYPE: ${{ secrets.OPENAI_API_TYPE }}
      OPENAI_API_ENDPOINT: ${{ secrets.OPENAI_API_ENDPOINT }}
      OPENAI_API_VERSION: ${{ secrets.OPENAI_API_VERSION }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ASSISTANT_ID: ${{ secrets.ASSISTANT_ID }}
      MODEL: ${{ secrets.MODEL }}

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11.4"
    - run: |
        pip install -r ./flows/reliefweb_chat/requirements.txt
    - run: |
        env
        cd flows/reliefweb_chat
        #pf connection create --file ./openai.yaml --set api_key=${{ secrets.OPENAI_API_KEY }}  --name open_ai_connection 
        pf connection create --file ./azure_openai.yaml --set api_key=${{ secrets.OPENAI_API_KEY }} --set api_base=${{ secrets.OPENAI_API_ENDPOINT }} --name azure_openai 
        pf run create --flow . --data data.jsonl --stream  --column-mapping query='${data.query}' context='${data.context}' --name base_run
        pf run show-details -n base_run
        pf run show-metrics -n base_run
        # pf run visualize -n base_run
        python3 check_evaluation_results.py

